export const metadata = {
  title: "BLAST 60 Ethanol Chiller | Chill 60 Gallons to -40°C | PermaCool",
  description: "PermaCool BLAST 60 ethanol chiller is designed to chill up to 60 gallons toward -40°C with PLC/HMI visibility and direct refrigerant efficiency."
}

const mainHtml = "<p class=\"eyebrow\">BLAST™ Product Line</p>\n    <h1>BLAST 60 Ethanol Chiller</h1>\n    <p>\n      Built for extraction operators who need compact, production-ready chilling performance, the BLAST 60 class is engineered\n      for fast pull-down, low-temp stability, and reliable PLC-based control.\n    </p>\n\n    <h2>Cascade refrigeration design</h2>\n    <p>\n      The Blast 60 is a <strong>cascade unit</strong>, meaning it uses <strong>two compressors working together</strong> instead of forcing one oversized system to do everything on its own.\n    </p>\n    <ul class=\"list\">\n      <li><strong>The primary refrigeration circuit</strong> is what directly chills the ethanol.</li>\n      <li><strong>The cascade refrigeration circuit</strong> cools the primary circuit, allowing the overall system to reach lower temperatures and stronger chilling performance.</li>\n    </ul>\n    <p>\n      That two-stage approach lets the Blast 60 produce high-powered chilling while still using <strong>common-sized condensers and widely serviceable components</strong>.\n    </p>\n\n    <h2>Why that matters in the field</h2>\n    <h3>1. Better low-temp performance</h3>\n    <p>\n      The cascade setup allows the machine to push colder and work harder than a simple single-stage setup in the same class.\n    </p>\n\n    <h3>2. Common parts, easier service</h3>\n    <p>\n      Because it relies on more standard component sizing instead of rare oversized hardware, it is:\n    </p>\n    <ul class=\"list\">\n      <li>easier to diagnose</li>\n      <li>easier to repair</li>\n      <li>cheaper to repair</li>\n      <li>easier to keep running long-term</li>\n    </ul>\n\n    <h3>3. Long life / maintainability</h3>\n    <p>\n      This is huge. It is <strong>easy to keep these going forever</strong>.\n    </p>\n    <ul class=\"list\">\n      <li>built for long-term serviceability</li>\n      <li>designed around repairable common components</li>\n      <li>easier to maintain over the life of the machine</li>\n      <li>avoids dependence on exotic hard-to-source oversized parts</li>\n    </ul>\n\n    <h2>Highlights</h2>\n    <ul class=\"list\">\n      <li>Designed for up to 60-gallon process class applications</li>\n      <li>Target low-temp operation around -40°C (config/facility dependent)</li>\n      <li>Direct refrigerant architecture with HVAC condenser integration</li>\n      <li>PLC/HMI operational visibility and compressor protection logic</li>\n    </ul>\n\n    <div class=\"cta-row mt\">\n      <a class=\"btn\" href=\"/contact-us\">Request BLAST 60 Pricing</a>\n      <a class=\"btn btn-ghost\" href=\"/ethanol-chilling-systems\">Compare Chiller Options</a>\n    </div>\n\n    <section class=\"related card\">\n      <h3>Related reading</h3>\n      <p><a href=\"/direct-refrigerant-vs-ln2\">Direct Refrigerant vs LN2</a> • <a href=\"/industrial-process-chiller-maintenance\">Maintenance Guide</a></p>\n    </section>"
const stickyHtml = "<div class=\"inner\">\n      <p>Need lead time + pricing for BLAST 60?</p>\n      <a class=\"btn\" href=\"/contact-us\">Request Pricing</a>\n    </div>"

export default function Page() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: mainHtml }} />
      {stickyHtml ? <div className="sticky-cta" dangerouslySetInnerHTML={{ __html: stickyHtml }} /> : null}
    </>
  )
}
